services:
  gameapp-redis:
    container_name: gameapp-redis
    image: redis:8.6.4-trixie
    ports:
      - "6380:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    volumes:
      - gameapp-redis:/data
  gameapp-database:
    image: mysql:9.7
    env_file:
      - .env
    ports:
      - "3308:3306"
    container_name: gameapp-database
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${GAMEAPP_MYSQL__USERNAME}
      MYSQL_PASSWORD: ${GAMEAPP_MYSQL__PASSWORD}

volumes:
  dbdata:
  gameapp-redis: